server:
  port: 10010
logging:
  level:
    root: info
    org:
      springframework:
        jdbc:
          core: debug
  pattern:
    console: "%d{HH:mm:ss} [%t][%-5level] %msg \\(%F:%L\\)%n"
spring:
  user-datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://${DDD_DB_URL}/users?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&tinyInt1isBit=false
    username: ${DDD_DB_ID}
    password: ${DDD_DB_PW}
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 20
      transaction-isolation: 1
      pool-name: pool-of-user
  auth-datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:authentication;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: admin
    password: admin
  h2:
    console:
      enabled: true
security:
  oauth2:
    client:
      client-id: auth_id
      client-secret: auth_secret
    resource:
      jwt:
        key-value: jwt_secret_key
