server:
  port: 10001
logging:
  level: info
    org.springframework.jdbc.core.JdbcTemplate: debug
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DDD_DB_URL}/users?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&tinyInt1isBit=false
    username: ${DDD_DB_ID}
    password: ${DDD_DB_PW}
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 20
      transaction-isolation: 1
      pool-name: pool-of-user

