security:
  oauty2:
    client:
      client-id: client
      client-secret: secret
    access-token-uri: local-auth.ddd.sns.com:10010/oauth/token
    user-authorization-uri: local-auth.ddd.sns.com:10010/oauth/authorize
    resource:
      jwt:
        key-value: jwt_secret_key
